### ISSUE TITLE
Migrate to ESP32 with Ethernet

### ISSUE THREAD

**Issue by nighteagle1974** [TillFleisch/ESPHome-Philips-Smart-Coffee#3]
Hello, is there a way to migrate to ESP32 with Ethernet like the WT32-ETH01 module?
I will also use it on a philips ep3246 - so the command may differ?

**Comment by TillFleisch** [comment]
Yes, it looks like this is possible. It has little to do with this custom component.
Check out the [ESPHome ](http://esphome.io/) webpage and [GitHub ](https://github.com/esphome/esphome) for more information on supported devices.
[Here ](https://community.home-assistant.io/t/how-i-installed-esphome-on-the-wt32-eth01/359027) someone has managed to get ESPHome running on a device like yours.

The commands on the ep3246 may be different. You can use the [UART Debug](https://esphome.io/components/uart.html#debugging) functionality to listen to messages.

**Comment by nighteagle1974** [comment]
Hello again,

so have bought a Philips 5000 Series - i will check if i can debug this traffic from the LCD - it loosk similar the other models. Should i post my experience hier or another place?

**Comment by TillFleisch** [comment]
I would recommend opening a new issue with a matching title. Also check out #6  as the mentioned machine has a display as well.

**Comment by DivanX10** [comment]
How did I find out that the motherboards of the 2000/3000/5000 series coffee machines are identical, only different control panels, so this connection scheme is the same for everyone, only the transistor is questionable. My screen turns on even without a transistor. The main problem is to catch the data from the management and I can't do it.

![image](https://user-images.githubusercontent.com/64090632/235682562-f0d3b3e6-84fb-440b-aa38-92d49132eb2f.png)


<details>
  <summary><b>Motherboards of coffee machines of different series 1000/2000/3000/5000</b></summary>
  

### Motherboard of the 1000/2000/3000 series coffee machine
![image](https://user-images.githubusercontent.com/64090632/235679677-1afdd2ff-0d1a-46ca-a196-6ca22b4a7cc3.png)
![image](https://user-images.githubusercontent.com/64090632/235679826-48e136ed-81da-4588-9de7-2e457e14b9c5.png)

### The motherboard of the 5000 series coffee machine
![image_2023-04-30_12-18-22](https://user-images.githubusercontent.com/64090632/235679953-c244e1f6-a06d-4805-8847-33e8a866fcb5.png)
</details>

<details>
  <summary><b>Below I lay out the scheme for the board 1.9.30.330.00._v10</b></summary>
  

### Circuit for the board 1.9.30.330.00._v10
![image](https://user-images.githubusercontent.com/64090632/235680514-d06c6cec-4a85-4e78-992d-5dcc911f7ac1.png)

***

### Communication with the front panel
![image](https://user-images.githubusercontent.com/64090632/235681241-3b70e743-519b-420f-9070-a691f5aba3e5.png)

***

### Sensors and valves
![image](https://user-images.githubusercontent.com/64090632/235681241-3b70e743-519b-420f-9070-a691f5aba3e5.png)

***

### Brewing device
![image](https://user-images.githubusercontent.com/64090632/235681314-fa17dda8-7b80-4875-af36-1c1777915e51.png)

***

### High voltage outputs
![image](https://user-images.githubusercontent.com/64090632/235681478-48cfb8ca-61f4-4021-be78-5d1b50993004.png)

***

### Power supply system
![image](https://user-images.githubusercontent.com/64090632/235681613-6377ec3d-c98f-44f9-a8f9-21d3fd5b22d5.png)

</details>


I'm trying to figure out from the logs what the command is for turning on coffee brewing and I still can't figure it out. I record by time and see the same records, but which one of them is responsible for the team, I do not see this

![image_2023-05-02_16-11-52](https://user-images.githubusercontent.com/64090632/235677024-3bf0c6da-50b7-4936-95aa-27f34ac85161.png)

We put ESP Home on Windows, then I created a shortcut, specified the command cmd.exe and the path to esphome
![image](https://user-images.githubusercontent.com/64090632/235677791-92ade4fc-9a62-49e6-b23a-2062b6f688c4.png)

Copy the project from ESPHome to the ESPHome folder on Windows and run the project
```
esphome logs smart-coffee-philips.yaml > philips5400_protocol.txt
```

Logs are recorded on the computer in a text file
![image](https://user-images.githubusercontent.com/64090632/235677215-423796f9-add6-4537-b93e-4a1a18e15e3c.png)
