### ISSUE TITLE
Turning on issue (EP3221)

### ISSUE THREAD

**Issue by machintrucbidule** [TillFleisch/ESPHome-Philips-Smart-Coffee#40]
Hi,

I have an issue when trying to turn on my coffee machine thru HA.
When clicking on the Power switch, the machine beeps, turns on; but the switch goes back to Off, and display remains off.

Logs:

> [01:17:10][D][switch:012]: 'Power' Turning ON.
> [01:17:10][D][uart_debug:114]: >>> D5:55:0A:01:03:00:0E:00:00:00:2A:10
> [01:17:10][D][uart_debug:114]: >>> D5:55:0A:01:03:00:0E:00:00:00:2A:10
> [01:17:10][D][uart_debug:114]: >>> D5:55:0A:01:03:00:0E:00:00:00:2A:10
> [01:17:10][D][uart_debug:114]: >>> D5:55:0A:01:03:00:0E:00:00:00:2A:10
> [01:17:10][D][uart_debug:114]: >>> D5:55:0A:01:03:00:0E:00:00:00:2A:10
> [01:17:10][D][uart_debug:114]: >>> D5:55:0A:01:03:00:0E:00:00:00:2A:10
> [01:17:10][D][uart_debug:114]: >>> D5:55:01:01:03:00:0E:00:00:00:01:25
> [01:17:10][D][uart_debug:114]: >>> D5:55:01:01:03:00:0E:00:00:00:01:25
> [01:17:10][D][uart_debug:114]: >>> D5:55:01:01:03:00:0E:00:00:00:01:25
> [01:17:10][D][uart_debug:114]: >>> D5:55:01:01:03:00:0E:00:00:00:01:25
> [01:17:10][D][uart_debug:114]: >>> D5:55:01:01:03:00:0E:00:00:00:01:25
> [01:17:10][D][uart_debug:114]: >>> D5:55:01:01:03:00:0E:00:00:00:01:25
> [01:17:10][W][component:214]: Component api took a long time for an operation (0.17 s).
> [01:17:10][W][component:215]: Components should block for at most 20-30ms.
> [01:17:10][D][uart_debug:114]: <<< D5:55:01:00:00:00:00:00:00:00:00:00
> [01:17:10][D][uart_debug:114]: <<< 00:00:00:00:00:06:26:D5:55:01:00:00
> [01:17:10][D][uart_debug:114]: >>> D5:55:01:00:00:00:00:00:00:00:00:00
> [01:17:10][D][uart_debug:114]: >>> 00:00:00:00:00:06:26:D5:55:01:00:00
> [01:17:10][D][number:012]: 'Coffee beans': Sending state nan
> [01:17:10][D][number:012]: 'Coffee size': Sending state nan
> [01:17:10][W][component:214]: Component esphome.coroutine took a long time for an operation (0.06 s).
> [01:17:10][W][component:215]: Components should block for at most 20-30ms.
> [01:17:11][W][component:214]: Component esphome.coroutine took a long time for an operation (0.75 s).
> [01:17:11][W][component:215]: Components should block for at most 20-30ms.
> [01:17:11][D][uart_debug:114]: <<< 00:00:00:00:00:00:00:00
> [01:17:11][D][uart_debug:114]: >>> 00:00:00:00:00:00:00:00
> [01:17:11][D][uart_debug:114]: >>> 00
> [01:17:11][D][uart_debug:114]: <<< 00
> [01:17:11][D][uart_debug:114]: <<< 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:11][D][uart_debug:114]: <<< 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:11][D][uart_debug:114]: <<< 26:D5:55:01:00:00:00:00:00:00:00:00
> [01:17:11][D][uart_debug:114]: >>> 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:11][D][uart_debug:114]: >>> 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:11][D][uart_debug:114]: >>> 26:D5:55:01:00:00:00:00:00:00:00:00
> [01:17:11][D][philips_power_switch:089]: Performed 1 power trip(s).
> [01:17:11][D][switch:055]: 'Power': Sending state ON
> [01:17:11][W][component:214]: Component esphome.coroutine took a long time for an operation (0.12 s).
> [01:17:11][W][component:215]: Components should block for at most 20-30ms.
> [01:17:11][D][uart_debug:114]: >>> 00:00
> [01:17:11][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:11][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:11][D][uart_debug:114]: <<< 00:00
> [01:17:11][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:11][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:11][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00
> [01:17:11][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00
> [01:17:11][D][uart_debug:114]: <<< 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:11][D][uart_debug:114]: <<< 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:11][D][uart_debug:114]: <<< 26:D5:55:01:00:00:00:00:00:00:00:00
> [01:17:11][D][uart_debug:114]: >>> 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:11][D][uart_debug:114]: >>> 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:12][D][uart_debug:114]: >>> 26:D5:55:01:00:00:00:00:00:00:00:00
> [01:17:12][W][component:214]: Component esphome.coroutine took a long time for an operation (0.19 s).
> [01:17:12][W][component:215]: Components should block for at most 20-30ms.
> [01:17:12][D][uart_debug:114]: >>> 00:00
> [01:17:12][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: <<< 00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:12][D][uart_debug:114]: <<< 26:D5:55:01:00:00:00:00:00:00:00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:12][D][uart_debug:114]: >>> 26:D5:55:01:00:00:00:00:00:00:00:00
> [01:17:12][W][component:214]: Component esphome.coroutine took a long time for an operation (0.19 s).
> [01:17:12][W][component:215]: Components should block for at most 20-30ms.
> [01:17:12][D][uart_debug:114]: >>> 00:00
> [01:17:12][D][uart_debug:114]: <<< 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 00:00
> [01:17:12][D][uart_debug:114]: >>> 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: >>> 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: >>> 04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: <<< 04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:12][D][uart_debug:114]: <<< 26:D5:55:00:03:00:07:00:00:00:00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:00:00:06:26:D5:55:01:00:00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:00:00:00:00:00:00:00:00:00:06
> [01:17:12][D][uart_debug:114]: >>> 26:D5:55:00:03:00:07:00:00:00:00:00
> [01:17:12][W][component:214]: Component esphome.coroutine took a long time for an operation (0.19 s).
> [01:17:12][W][component:215]: Components should block for at most 20-30ms.
> [01:17:12][D][uart_debug:114]: >>> 00:00
> [01:17:12][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: <<< 00:00
> [01:17:12][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:03:2C:D5:55:00:03:00:07
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:00:00:00:00:00:00:00:03
> [01:17:12][D][uart_debug:114]: <<< 2C:D5:55:00:03:00:07:00:00:00:00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:00:00:03:2C:D5:55:00:03:00:07
> [01:17:12][D][uart_debug:114]: >>> 00:00:00:00:00:00:00:00:00:00:00:03
> [01:17:12][D][uart_debug:114]: >>> 2C:D5:55:00:03:00:07:00:00:00:00:00
> [01:17:12][W][component:214]: Component esphome.coroutine took a long time for an operation (0.19 s).
> [01:17:12][W][component:215]: Components should block for at most 20-30ms.
> [01:17:12][D][uart_debug:114]: >>> 00:00
> [01:17:12][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: <<< 00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:03:2C:D5:55:00:00:00:03
> [01:17:12][D][uart_debug:114]: <<< 38:00:00:00:00:00:00:00:00:00:00:2C
> [01:17:12][D][uart_debug:114]: <<< 1B:D5:55:00:00:00:03:38:00:00:00:00
> [01:17:12][D][uart_debug:114]: >>> 00:00:00:00:03:2C:D5:55:00:00:00:03
> [01:17:12][D][uart_debug:114]: >>> 38:00:00:00:00:00:00:00:00:00:00:2C
> [01:17:12][D][uart_debug:114]: >>> 1B:D5:55:00:00:00:03:38:00:00:00:00
> [01:17:12][W][component:214]: Component esphome.coroutine took a long time for an operation (0.18 s).
> [01:17:12][W][component:215]: Components should block for at most 20-30ms.
> [01:17:12][D][uart_debug:114]: >>> 00:00
> [01:17:12][D][uart_debug:114]: <<< 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: <<< 00:00
> [01:17:12][D][uart_debug:114]: >>> 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: >>> 04:02:04:00:00:00:2F:0D:D5:55:00:01
> [01:17:12][D][uart_debug:114]: >>> 04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: <<< 04:02:04:00:00:00:2F:0D
> [01:17:12][D][uart_debug:114]: <<< 00:00:00:00:2C:1B:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: <<< 18:38:00:00:00:00:00:00:00:00:00:21
> [01:17:13][D][uart_debug:114]: <<< 09:D5:55:00:00:00:00:18:38:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 00:00:00:00:2C:1B:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 18:38:00:00:00:00:00:00:00:00:00:21
> [01:17:13][D][uart_debug:114]: >>> 09:D5:55:00:00:00:00:18:38:00:00:00
> [01:17:13][W][component:214]: Component esphome.coroutine took a long time for an operation (0.18 s).
> [01:17:13][W][component:215]: Components should block for at most 20-30ms.
> [01:17:13][D][uart_debug:114]: >>> 00:00
> [01:17:13][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:13][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:13][D][uart_debug:114]: <<< 00:00
> [01:17:13][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:13][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:13][D][uart_debug:114]: >>> D5:55:00:01:04:02:04:00
> [01:17:13][D][uart_debug:114]: <<< D5:55:00:01:04:02:04:00
> [01:17:13][D][uart_debug:114]: <<< 00:00:00:00:21:09:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: <<< 18:38:00:00:00:00:00:00:00:00:00:21
> [01:17:13][D][uart_debug:114]: <<< 09:D5:55:00:00:00:00:18:38:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 00:00:00:00:21:09:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 18:38:00:00:00:00:00:00:00:00:00:21
> [01:17:13][D][uart_debug:114]: >>> 09:D5:55:00:00:00:00:18:38:00:00:00
> [01:17:13][W][component:214]: Component esphome.coroutine took a long time for an operation (0.18 s).
> [01:17:13][W][component:215]: Components should block for at most 20-30ms.
> [01:17:13][D][uart_debug:114]: >>> 00:00
> [01:17:13][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:13][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:13][D][uart_debug:114]: <<< 00:00
> [01:17:13][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:13][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01:04:02:04:00
> [01:17:13][D][uart_debug:114]: >>> 00:00:2F:0D:D5:55:00:01
> [01:17:13][D][uart_debug:114]: <<< 00:00:2F:0D:D5:55:00:01
> [01:17:13][D][uart_debug:114]: <<< 00:00:00:00:21:09:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: <<< 07:18:00:00:00:00:00:00:00:00:00:21
> [01:17:13][D][uart_debug:114]: <<< 30:D5:55:00:00:00:00:07:18:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 00:00:00:00:21:09:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 07:18:00:00:00:00:00:00:00:00:00:21
> [01:17:13][D][uart_debug:114]: >>> 30:D5:55:00:00:00:00:07:18:00:00:00
> [01:17:13][W][component:214]: Component esphome.coroutine took a long time for an operation (0.19 s).
> [01:17:13][W][component:215]: Components should block for at most 20-30ms.
> [01:17:13][D][uart_debug:114]: >>> 00:00
> [01:17:13][D][uart_debug:114]: <<< 04:02:04:00:00:00:2F:0D:00:2F:0D:D5
> [01:17:13][D][uart_debug:114]: <<< 55:00:01:04:02:04:00:00:00:2F:0D:D5
> [01:17:13][D][uart_debug:114]: <<< 00:00
> [01:17:13][D][uart_debug:114]: >>> 04:02:04:00:00:00:2F:0D:00:2F:0D:D5
> [01:17:13][D][uart_debug:114]: >>> 55:00:01:04:02:04:00:00:00:2F:0D:D5
> [01:17:13][D][uart_debug:114]: >>> 55:00:01:04:02:04:00:00
> [01:17:13][D][uart_debug:114]: <<< 55:00:01:04:02:04:00:00
> [01:17:13][D][uart_debug:114]: <<< 00:00:00:00:21:30:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: <<< 07:18:00:00:00:00:00:00:00:00:00:21
> [01:17:13][D][uart_debug:114]: >>> 00:00:00:00:21:30:D5:55:00:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 07:18:00:00:00:00:00:00:00:00:00:21
> [01:17:13][W][component:214]: Component esphome.coroutine took a long time for an operation (0.15 s).
> [01:17:13][W][component:215]: Components should block for at most 20-30ms.
> [01:17:13][D][uart_debug:114]: >>> 30
> [01:17:13][D][uart_debug:114]: <<< 00:2F:0D:D5:55:00:01:04:02:04:00:00
> [01:17:13][D][uart_debug:114]: <<< 00:2F:0D:D5:55:00:01:04:02:04:00:00
> [01:17:13][D][uart_debug:114]: <<< 30
> [01:17:13][D][uart_debug:114]: >>> 00:2F:0D:D5:55:00:01:04:02:04:00:00
> [01:17:13][D][uart_debug:114]: >>> 00:2F:0D:D5:55:00:01:04:02:04:00:00
> [01:17:13][D][uart_debug:114]: >>> 00:2F:0D:D5:55:00:01:04
> [01:17:13][D][uart_debug:114]: <<< D5:55:00:00:07:00:03:00:00:00:00:00
> [01:17:13][D][uart_debug:114]: <<< 00:2F:0D:D5:55:00:01:04
> [01:17:13][D][uart_debug:114]: >>> D5:55:00:00:07:00:03:00:00:00:00:00
> [01:17:13][W][component:214]: Component esphome.coroutine took a long time for an operation (0.13 s).
> [01:17:13][W][component:215]: Components should block for at most 20-30ms.
> [01:17:13][D][uart_debug:114]: >>> 00:00:00:00:00:05:21
> [01:17:13][D][uart_debug:114]: <<< 02:04:00:00:00:2F:0D:D5:55:00:01:04
> [01:17:13][D][uart_debug:114]: <<< 02:04:00:00:00:2F:0D:D5:55:00:01:04
> [01:17:13][D][uart_debug:114]: <<< 00:00:00:00:00:05:21
> [01:17:13][D][uart_debug:114]: >>> 02:04:00:00:00:2F:0D:D5:55:00:01:04
> [01:17:13][D][uart_debug:114]: >>> 02:04:00:00:00:2F:0D:D5:55:00:01:04
> [01:17:13][D][uart_debug:114]: >>> 02:04:00:00:00:2F:0D:D5
> [01:17:13][D][uart_debug:114]: <<< D5:55:00:00:07:00:03:00:00:00:00:00
> [01:17:13][D][uart_debug:114]: <<< 00:00:00:00:00:05:21:D5:55:00:00:07
> [01:17:13][D][uart_debug:114]: <<< 02:04:00:00:00:2F:0D:D5
> [01:17:13][D][uart_debug:114]: >>> D5:55:00:00:07:00:03:00:00:00:00:00
> [01:17:13][D][uart_debug:114]: >>> 00:00:00:00:00:05:21:D5:55:00:00:07
> [01:17:14][W][component:214]: Component esphome.coroutine took a long time for an operation (0.16 s).
> [01:17:14][W][component:215]: Components should block for at most 20-30ms.
> [01:17:14][D][uart_debug:114]: >>> 00:03:00:00:00:00:00:00
> [01:17:14][D][uart_debug:114]: <<< 00:03:00:00:00:00:00:00
> [01:17:14][D][uart_debug:114]: >>> 55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:14][D][uart_debug:114]: <<< 55:00:01:04:02:04:00:00:00:2F:0D
> [01:17:14][W][component:214]: Component esphome.coroutine took a long time for an operation (0.05 s).
> [01:17:14][W][component:215]: Components should block for at most 20-30ms.
> [01:17:14][D][uart_debug:114]: <<< 00:00:00:00:05:21
> [01:17:14][D][uart_debug:114]: >>> 00:00:00:00:05:21
> [01:17:14][D][switch:055]: 'Power': Sending state OFF`

If I click again on the Power switch, then display turns on.
No issue for turning off, but if I try to turn it on again, I face the same issue again.

I tried to update the "power_message_repetitions" (5/25/50/200), or the "power_trip_delay" (500ms/750ms/1000ms/2000ms), without any success.
Tried also to update the "MAX_POWER_TRIP_COUNT" from the power.h, but no change again.

Appart from that, when turned on, all functionalities seems to respond (but didn't tried a lot yet).

Hardware : 
Philips EP-3221
ESP32 S2 Mini
IRLZ44N Mofset, with 220 ohms resistor

Config (haven't changed anything yet about buttons/numbers configuration, I'll see that later):

```
esphome:
  name: machine-cafe
  friendly_name: machine-cafe

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:
  # Disable serial logging
  baud_rate: 0


external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@series-3200
    refresh: 0s

uart:
  # UART connected to the mainboard
  - tx_pin: GPIO39
    rx_pin: GPIO37   
    baud_rate: 115200
    id: uart_mainboard
    debug:
      after:
        bytes: 12

  # UART connected to the display
  - tx_pin: GPIO17
    rx_pin: GPIO21  
    baud_rate: 115200
    id: uart_display   
    debug:
      after:
        bytes: 12

philips_coffee_machine:
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO35
  id: philip
  model: EP_3243
  power_message_repetitions: 5
  power_trip_delay: 750ms

text_sensor:
  - platform: philips_coffee_machine
    controller_id: philip
    id: status
    name: "Status"

switch:
  - platform: philips_coffee_machine
    controller_id: philip
    name: "Power"
    clean: false
    icon: mdi:coffee-maker

button:
  - platform: philips_coffee_machine
    controller_id: philip
    action: MAKE_COFFEE
    name: "Make Coffee"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philip
    action: SELECT_HOT_WATER
    name: "Select Hot Water"
    icon: mdi:tea

  - platform: philips_coffee_machine
    controller_id: philip
    action: PLAY_PAUSE
    name: "Select play/pause"
    icon: mdi:play-pause

number:
  - platform: philips_coffee_machine
    type: bean
    name: "Coffee beans"
    controller_id: philip
    status_sensor_id: status
    source: COFFEE

  - platform: philips_coffee_machine
    type: size
    name: "Coffee size"
    controller_id: philip
    status_sensor_id: status
    source: COFFEE
```

**Comment by TillFleisch** [comment]
Please note that the series-3200 branch/draft is still under development.
Since this issue is EP-3221 related (which is not currently supported) and you already have an open issue regarding the EP-3221, let's move this conversation to #36 so everything EP-3221 related can be found there.
