### ISSUE TITLE
Idle state not detected on some machines

### ISSUE THREAD

**Issue by davidepanato** [TillFleisch/ESPHome-Philips-Smart-Coffee#41]
Ciao Till, thanks for your good job, after latest changes I was also able to power on my coffe machine (previously this was not working but it has been fixed by message repetition).
I'm now moving forward with integrating all functionalities and I think that my machine 2220 has some difference in the protocol from yours since coffee beans and coffee size are not detected. Also when powering on I see the state moving from off to cleaning but never to ready.
Is there an easy way to print the messages shared between motherboard and display to try to debug the protocol? I have tried uart debugging but it prints tons of messages.

Another strange behavior is also happening sometimes, when powering on I hear ad duplicated "BIP" and display remains stuck with aqua clean icon blinking.

Thanks for your support
Davide

**Comment by davidepanato** [comment]
Hello Tiil, I still need to setup everything to collect the uart logs, as soon as I'll do I'll share the result.
I checked in the meantime my machine label (bought on summer 2023) and all values are aligned with yours.

Davide

**Comment by mikulik86** [comment]
Just FYI, I had to change the 7th byte in the Status sensor for Idle state to be recognized on my EP2224/40.

From:
https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/blob/866fb171cdeea1e0dfbdf0aad2cdfc57f3bc1bf7/components/philips_coffee_machine/text_sensor/status_sensor.cpp#L46

To:
`if (data[3] == led_on && data[4] == led_on && data[5] == led_on && data[6] == led_third)`

<br/>
Btw @TillFleisch could you explain what exactly do you mean by led_second and led_third?

https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/blob/866fb171cdeea1e0dfbdf0aad2cdfc57f3bc1bf7/components/philips_coffee_machine/commands.h#L17-L18

**Comment by TillFleisch** [comment]
Those values were recovered by observing the bus, they represent different states which the leds can take. You can find more information here: [protocol.md](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/blob/main/protocol.md)

**Comment by mikulik86** [comment]
OK, so you mean second/third STATE of a led. Got it.

**Comment by isocron** [comment]
Hi there.

I have an EP2220, DAP NL9206AB-4a Drachten, EP2220/10 882871110010. MAIN 421945017972 UI 421945055571 from Spring 2023.
I have the same error that the status gets stuck at cleaning and brewing. That is, it does not detect Idle. Tried the fix from mikulik86 and now the status changes to Idle, as intended.

**Comment by TillFleisch** [comment]
Sounds like a difference in display units (i.e. different version). I will try `data[6] != led_off` when I get home, which should work on both machines/versions, to see if this change has any unwanted side-effects.
