### ISSUE TITLE
4300 series

### ISSUE THREAD

**Issue by IvanSerevko** [TillFleisch/ESPHome-Philips-Smart-Coffee#84]
Hello, is it possible to do this for the 4300 series? thank you

**Comment by TillFleisch** [comment]
Hey, sorry for the late response.
The current state of this repository does not support the `4300` series and it probably won't any time soon.
A similar/adjacent project may be possible for the `4300` series. Please have a look at [a related discussion regarding the 5400 series](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/issues/6) for more details. Maybe, the therein presented solution also works for
